<?php
return [

    1=> ["series_id"=>1, "series_set_id"=>1],
    2=> ["series_id"=>2, "series_set_id"=>1],
    3=> ["series_id"=>1, "series_set_id"=>1],
    5=> ["series_id"=>1, "series_set_id"=>1],
    6=> ["series_id"=>1, "series_set_id"=>1],
    7=> ["series_id"=>1, "series_set_id"=>1],
    8=> ["series_id"=>2, "series_set_id"=>1],
    9=> ["series_id"=>2, "series_set_id"=>1],
    10=> ["series_id"=>2, "series_set_id"=>1],
    11=> ["series_id"=>1, "series_set_id"=>1],
    12=> ["series_id"=>2, "series_set_id"=>1],
    13=> ["series_id"=>3, "series_set_id"=>1],
    14=> ["series_id"=>13, "series_set_id"=>1],
    20=> ["series_id"=>15, "series_set_id"=>1],
    21=> ["series_id"=>15, "series_set_id"=>1],
    22=> ["series_id"=>15, "series_set_id"=>1],
    23=> ["series_id"=>1, "series_set_id"=>1],
    24=> ["series_id"=>1, "series_set_id"=>1],
    25=> ["series_id"=>16, "series_set_id"=>2],
    26=> ["series_id"=>16, "series_set_id"=>2],
    27=> ["series_id"=>16, "series_set_id"=>2],
    28=> ["series_id"=>16, "series_set_id"=>2],
    29=> ["series_id"=>16, "series_set_id"=>2],
    30=> ["series_id"=>16, "series_set_id"=>2],
    31=> ["series_id"=>16, "series_set_id"=>2],
    32=> ["series_id"=>16, "series_set_id"=>2],
    33=> ["series_id"=>16, "series_set_id"=>2],
    34=> ["series_id"=>17, "series_set_id"=>2],
    35=> ["series_id"=>17, "series_set_id"=>2],
    37=> ["series_id"=>17, "series_set_id"=>2],
    38=> ["series_id"=>17, "series_set_id"=>2],
    39=> ["series_id"=>17, "series_set_id"=>2],
    40=> ["series_id"=>17, "series_set_id"=>2],
    41=> ["series_id"=>17, "series_set_id"=>2],
    42=> ["series_id"=>17, "series_set_id"=>2],
    43=> ["series_id"=>17, "series_set_id"=>2],
    44=> ["series_id"=>18, "series_set_id"=>2],
    45=> ["series_id"=>18, "series_set_id"=>2],
    46=> ["series_id"=>18, "series_set_id"=>2],
    47=> ["series_id"=>18, "series_set_id"=>2],
    48=> ["series_id"=>18, "series_set_id"=>2],
    49=> ["series_id"=>18, "series_set_id"=>2],
    50=> ["series_id"=>18, "series_set_id"=>2],
    51=> ["series_id"=>18, "series_set_id"=>2],
    52=> ["series_id"=>18, "series_set_id"=>2],
    53=> ["series_id"=>19, "series_set_id"=>1],

    54=> ["series_id"=>20, "series_set_id"=>1],
    55=> ["series_id"=>20, "series_set_id"=>1],
    56=> ["series_id"=>20, "series_set_id"=>1],
    57=> ["series_id"=>20, "series_set_id"=>1],
    58=> ["series_id"=>20, "series_set_id"=>1],
    59=> ["series_id"=>20, "series_set_id"=>1],

];
