<?php
return [
    'root_path' => app_path() . '/../widgets/',
    'data_path' => app_path() . '/../widgets/data/',
    'js_data_path' => app_path() . '/../widgets/jsdata/',
    'widget' => [
        'lotteries' => [
            'type'       => 'select',
            'main'       => 'Lottery',
            'children'   => '',
            'level'      => 1,
            'selectName' => 'lottery_id',
            'output'     => 'html',
            'fileName'   => 'lotteries',
        ],
        'lottery-ways' => [
            'type'     => 'select',
            'main'     => 'Lottery',
            'children' => 'LotteryWay',
            'level'    =>  2,
            'parent'   => 'lottery_id',
            'output'   => 'json',
            'fileName' => 'lottery-ways',
        ],
        'districts' => [
            'type'     => 'select',
            'main'     => 'District',
            'children' => 'District',
            'level'    =>  2,
            'output'   => 'json',
            'fileName' => 'districts',
        ],
        'banks' =>  [
            'type'       => 'select',
            'main'       => 'Bank',
            'children'   => '',
            'level'      => 1,
            'selectName' => 'bank_id',
            'output'     => 'html',
            'fileName'   => 'banks',
        ],
        // 'bank-cards' =>  [
        //     'type'       => 'select',
        //     'main'       => 'UserBankCard',
        //     'children'   => '',
        //     'level'      => 1,
        //     'selectName' => 'bank_card_id',
        //     'output'     => 'html',
        //     'name'       => 'account',
        //     'fileName'   => 'bank-cards',
        // ],
        'way-main-groups' => [
            'type'       => 'select',
            'main'       => 'WayGroup',
            'children'   => '',
            'name'       => 'title',
            'level'      => 1,
            'selectName' => 'way_group_id',
            'output'     => 'html',
            'fileName'   => 'way-main-groups',
        ],
        'way-groups' => [
            'type'     => 'select',
            'main'     => 'WayGroup',
            'children' => 'WayGroup',
            'name'     => 'title',
            'level'    => 2,
            'output'   => 'json',
            'fileName' => 'way-groups',
        ],
        'series-way-groups-way-group-ways' => [
            'type'     => 'select',
            'main'     => 'Series',
            'children' => 'WayGroup',
            'grandson' => 'WayGroupWay',
            'name1'    => 'name',
            'name2'    => 'title',
            'parent1'  => 'series_id',
            'parent2'  => 'parent_id',
            'parent3'  => 'group_id',
            'level'    => 3,
            'output'   => 'json',
            'fileName' => 'series-way-groups-way-group-ways',
        ],
        'lottery-series' => [
            'type'       => 'select',
            'main'       => 'Lottery',
            'children'   => '',
            'name'       => 'name',
            'friendly'   => 'friendly_name',
            'extraParam' => ['series_id', 'status'],
            'level'      => 1,
            'output'     => 'json',
            'fileName'   => 'lottery-series',
            'dataName'   => 'lotteriesWithSeriesId',
        ],
    ]
];